### ISSUE TITLE
System.Runtime.InteropServices.SEHException: 'External component has thrown an exception.'

### ISSUE THREAD

**Issue by EricBallard** [robmikh/ManagedScreenshotDemo#1]
**Unable to create GraphicsCaptureItem from handle - consistently getting this error when trying to capture "World of Warcraft" (Classic) window.**

**DETAILS:**
This occurs randomly, I've been trying to identify the problem for days now with no avail.

I am unable to identify why this occurs. I have verified the application is using DirectX11 API (This application does have a DirectX11 Legacy option - there is no difference in results when using this option). Additionally I've ensured the application is rendering with the 1 and only available GPU on this system.

**TROUBLESHOOTING:**
I have tried a various amount of system shutdown/restarts.

I have tried forcing the application to use DirectX11 by launching with arguments.

I have tried several combinations of running both VS and the target application as administrator, restarting, and have experienced no relief. 

I have tried toggle the target application between render api version and fullscreen/windowed mode - no affect has been observed.

Additionally I've tried capturing other windows, like Paint, and these windows are captured fine.

Additionally, OBS - a popular screen recording application - supports Graphics.Capture as one of several capture methods. 
It seems there is a common issue with capturing this target window?

https://obsproject.com/forum/threads/cant-capture-wow.54404/

This problem seemingly randomly occurs, and just after some time I can capture the target window no problem.
I cannot identify a solution as the steps I believe to fix the issue will prove to have no affect when the problem re-occurs and it seems it only start to work again at random.

Also I am trying to test with other Dx11 applications but the one I've downloaded here "Mecha Demo"
https://www.guru3d.com/files-details/amd-mecha-directx-11-demo.html

Throws an error creating the staging texture
var stagingTexture = new SharpDX.Direct3D11.Texture2D(d3dDevice, description);

SharpDX.SharpDXException: 'HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.'

So if you know any other DirectX11 applications I could use as a control that'd be great!

Lastly, I am using the code in this demo verbatim, and obtaining the window handle and item as so:

```
[DllImport("user32.dll")]
 static extern IntPtr FindWindow(string lpClassName, string lpWindowName);

var handle = FindWindow(null, "World of Warcraft");
var item = CaptureHelper.CreateItemForWindow(handle); var size = item.Size;
```

**ERROR:**
Error Dump (142MB)
https://www.dropbox.com/s/a9ll9rpletg8t79/ManagedScreenshotDemo.dmp?dl=0

![image](https://user-images.githubusercontent.com/1421228/128561401-d6c6d812-482a-4d09-9e54-bc23f0cd874f.png)

**SYSTEM:**

Reading through some threads of end-users experiencing this issue - it would seem that one potential consistency in this issue - I've identified a few of us are using similar GPU's. (RX480 / RX580)

```
Gpu XFX Radeon RX 480 8GB
Processor	AMD Ryzen 7 1700X Eight-Core Processor            3.40 GHz
Installed RAM	16.0 GB
System type	64-bit operating system, x64-based processor

Edition	Windows 10 Pro N
Version	20H2
Installed on	‎3/‎9/‎2021
OS build	19042.1110
Experience	Windows Feature Experience Pack 120.2212.3530.0

```

**Comment by robmikh** [comment]
If things are blowing up on getting a GraphicsCaptureItem, it's likely not related to Direct3D11. I would guess that the window structure of the application has confused the system and we picked the wrong window to represent the content. Similar to this issue: 
https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/issues/65. If you want to take a peek, I would open up Spy++ and look at WoW's window structure. I'll see if I can get it installed on a test machine and check for myself.

As for your issue with the Mecha Demo, I'm unable to reproduce it, but I'm using a different GPU:
![image](https://user-images.githubusercontent.com/7089228/128566210-6798b83f-5763-40ec-9ec3-d4428a68d295.png)

Could you dump the description before it fails creating the staging texture? Or if you could collect a memory dump when it fails, I could take a look.

I know Source engine games like Counter Strike GO and DOTA 2 using the Direct3D11 backend work fine. Also the basic D3D11 cube from the Visual Studio templates should work too.

**Comment by robmikh** [comment]
Hmmmm... I'm getting this with the Win32CaptureSample:

![image](https://user-images.githubusercontent.com/7089228/128567265-d77563fa-2549-41c7-8718-e9a8176c329e.png)

Could you grab the latest release from [here](https://github.com/robmikh/Win32CaptureSample/releases) and see if you can still reproduce your issue with it?

**Comment by robmikh** [comment]
Also, does the Xbox Game Bar work for you with these games?

**Comment by EricBallard** [comment]
Legend! Using Spy++ I was able to identify the classname of the target window (Inspect would stop responding)

`            var handle = FindWindow("GxWindowClass", "World of Warcraft");
`
Passing both parameters seems to work flawlessly - It even seems to be able to capture the window when in DirectX12.

Thanks for the awesome example and response!


One last thing, kind of a noob question but I'm new to .net stack. I see this demo targets `net5.0-windows10.0.19041.0` however I would like to use [GraphicsCaptureSession.IsBorderRequired ](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturesession.isborderrequired?view=winrt-20348#Windows_Graphics_Capture_GraphicsCaptureSession_IsBorderRequired) which looks like it wasn't added until "Windows 10, version 2104 (introduced in 10.0.20348.0)".

Well.. I updated Windows as much as I could and I'm sitting at 
```
Version	21H1
OS build	19043.1110
Experience	Windows Feature Experience Pack 120.2212.3530.0
```

So if I set the target framework to `net5.0-windows10.0.20348.0` the API method is exposed in the ide however on run it ​gives me an "InvalidCastException" 
```
Unhandled exception. System.InvalidCastException: Specified cast is not valid.
  ​at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
  ​at WinRT.IObjectReference.As[T](Guid iid)
  ​at WinRT.SingleInterfaceOptimizedObject..ctor(Type type, IObjectReference objRef)
  ​at Windows.Graphics.Capture.GraphicsCaptureSession.<.ctor>b__12_2()
  ​at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
  ​at System.Lazy`1.CreateValue()
  ​at System.Lazy`1.get_Value()
  ​at Windows.Graphics.Capture.GraphicsCaptureSession.AsInternal(InterfaceTag`1 _)
  ​at Windows.Graphics.Capture.GraphicsCaptureSession.get_IsBorderRequired()
```

I believe this issue is because I'm using the wrong version of Windows SDK? 
The latest version in  visual studio installer is 110.0.19041.0 however I see here - 10.0.20348.0 is available!
https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/
​
I need to install this? Do I need to add it as a component to vs or just set the target framework?
Do end user's need this sdk for it to work - why doesn't it work on my PC without it despite being up to date?

I greatly appreciate any insight! Cheers - thanks for all your help!

**Comment by robmikh** [comment]
I'm glad you were able to get it working! As for using newer APIs and versioning...

The Windows.Graphics.Capture API is part of the Windows runtime, and its implementation is shipped with the operating system. The SDK only contains the interfaces and metadata about APIs provided by the system. Users of your application do not need the SDK for it run properly, they just need to have the appropriate version of Windows installed.

Various APIs provide mechanisms to detect what is available from the system. One way is to use the `ApiInformation` API to query the existence of properties or functions. For example:

```csharp
using Windows.Foundation.Metadata;

if (ApiInformation.IsPropertyPresent(
    typeof(GraphicsCaptureSession).FullName,
    nameof(GraphicsCaptureSession.IsBorderRequired)))
{
    // Do something special
}
```

Keep in mind that `ApiInformation` parses the metadata found on the machine, so it can become expensive to check repeatedly. You should probably check this at the beginning of your program and mark some flags. 

As for why you don't have the version required for the `GraphicsCaptureSession.IsBorderRequired` API after updating, it's because the API is still in preview (as noted at the bottom of the MSDN page). This API will become broadly available in a future release of Windows. In the mean time, you can access the API if you install a [Windows Insider](https://insider.windows.com/en-us/) build. There's also [this page](https://docs.microsoft.com/en-us/windows-insider/flight-hub/) that contains a history of published Insider builds and SDKs.

Hopefully that clears up the confusion!
