### ISSUE TITLE
Is it possible to set a max limit for `FrameArrived` event callback?

### ISSUE THREAD

**Issue by GF-Huang** [robmikh/ManagedScreenshotDemo#2]
First, thanks for your demo.

I encapsulated your code into a `WgcCapturer` class. The basic logic remains unchanged. I only added a `FrameCaptured` event to notify that new frame data is available. For ease of reading, I only show the code that I think is necessary. 

And I only use **Staging Texture**, I don't use **Swap Chain**.

I have discovered some phenomena: 
1. When capturing the entire screen (1920*1080), the mouse does not move and the screen remains unchanged, and the FPS will drop to 15 ~ 20. This is make sense, reducing unnecessary captures when the screen does not change can reduce resource usage. 
2. But when I keep the config of 1 and keep shaking the mouse, the FPS will rise to 30 ~ 45. And, I found that I couldn't hit 60 FPS.
3. Keep the config of 2, but change `NumberOfFramePoolBuffers` to 2. I found that I could exceed 60FPS and sometimes reach 70 ~ 80. In details, when I open the browser and play the video in the browser, it reach 70 ~ 80+. When I stop playing video but  keep shaking mouse, it keep around 60.
Note, **Keep the config of 2** means I need to shaking my mouse repeatedly, if I stop shaking, the FPS will down to 15 ~ 20 aslo.
4. For comparison, I added code to this project(https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/tree/master/dotnet/WPF/ScreenCapture) that counts FPS and captures the entire screen. I find it stays at a stable 60 FPS and I have no idea why this is happening (maybe caused by swap chain?). I even increased `NumberOfFramePoolBuffers` to 5 but got the same result. And same to 3, playing video will reach 70 ~ 80+. When stop the video, I don't need to shake mouse, it keep 60 stable.

The above are some phenomena I observed, but my problem is that in my use case (without swap chain) sometimes the FPS will be higher than 60 to 70 ~ 80, too many captures are meaningless for my use case , I worry about whether too high FPS will waste unnecessary resources. So, is there a way to stably limit the maximum FPS of `FrameArrived`?

### WgcCapturer 
```cs
class WgcCapturer {
    ...
    private void FramePool_FrameArrived(Direct3D11CaptureFramePool sender, object args) {
        ...
        if (sizeChanged || _frameData == null)
            _frameData = new byte[frameSize.Width * frameSize.Height * 4]; // 4 bytes per pixel

        unsafe {
            fixed (byte* bytesPointer = _frameData) {
                ... 
            }
        }

        FrameCaptured?.Invoke(this, _frameData, new Size(frameSize.Width, frameSize.Height));    
        ...
    }
}
```

### Usage
```cs
// I found that increase the frame pool buffers, it will increase the upper limit of capture FPS.
using var capturer = new WgcCapturer { NumberOfFramePoolBuffers = 1 /*for Direct3D11CaptureFramePool.CreateFreeThreaded()*/ }; 

int frames = 0;
var watch = Stopwatch.StartNew();

capturer.FrameCaptured += (WgcCapturer capturer, ReadOnlySpan<byte> frameData, Size frameSize) => {
    frames++;

    if (watch.Elapsed.TotalSeconds >= 1) {
        Console.WriteLine($"FPS: {frames / watch.Elapsed.TotalSeconds:N1}"); // Print FPS to console
        frames = 0;
        watch.Restart();
    }
};

capturer.Start();
```

**Comment by robmikh** [comment]
As you've noticed, we try not to push new frames if nothing has changed on screen. The reason the swap chain causes the frame rate to go up is because it changes the screen, forcing an update. This is also similar to the behavior of moving the mouse.

If you only use 1 buffer, keep in mind that if you're holding onto it, the DWM won't have any buffers to draw into. This is why the framerate is higher when you use 2 or more buffers in the frame pool. This is the same principle as a swap chain, except in reverse.

For currently released versions of Windows, your best bet is to either purposefully starve the DWM of frames (by holding onto Direct3D11CaptureFrame objects), or by ignoring frames that come in too soon by looking at the timestamps. In an upcoming release, you will be able to provide your desired minimum update interval, and we will honor that. Unfortunately I don't have a timeline on when that feature is shipping.

**Comment by GF-Huang** [comment]
@robmikh Thanks for your detailed answer. 
> your best bet is to either purposefully starve the DWM of frames (by holding onto Direct3D11CaptureFrame objects)

I don't quite understand this. Can you explain in detail how to do it? Thank you.

**Comment by robmikh** [comment]
When you create a frame pool, you specify how many buffers it has. These buffers are given to you as Direct3D11CaptureFrame objects. The idea is to hold onto all of them, which will cause the DWM to stop drawing frames for you. When you want a new frame, you Close/Dispose one of the frame objects.

[robmikh/SimpleRecorder](https://github.com/robmikh/SimpleRecorder) does something similar. It creates a frame pool with one buffer and uses its control over the lifetime of that buffer to control DWM's rendering.
